apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: theme-wring-menu-item
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: text
      name: icon
      label: 图标icon
      placeholder: "例如: czs czs-home-l"
---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: theme-wring-page
spec:
  targetRef:
    group: content.halo.run
    kind: SinglePage
  formSchema:
    - $formkit: switch
      name: hideCover
      label: 隐藏封面图
      value: false
      onValue: "true"
      offValue: "false"
    - $formkit: switch
      name: hideTitle
      label: 隐藏标题
      value: false
      onValue: "true"
      offValue: "false"
    - $formkit: switch
      name: hideMeta
      label: 隐藏元信息
      value: false
      onValue: "true"
      offValue: "false"
---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: theme-wing-link-group
spec:
  targetRef:
    group: core.halo.run
    kind: LinkGroup
  formSchema:
    - $formkit: select
      name: theme-wing/link-group-style
      label: 卡片样式
      options:
        - label: 默认样式
          value: "default"
        - label: 推荐样式
          value: "recommend"
        - label: 失联样式
          value: "lost"
