apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-Wing
spec:
  displayName: Wing
  author:
    name: 二歪同学
    website: "https://waistu.com"
  description: 一款简洁流畅、数据驱动，响应式主题，移植自WordPress主题Wing
  logo: "/themes/theme-wing/assets/img/logo.png"
  homepage: "https://github.com/waistu/halo-theme-Wing#readme"
  repo: "https://github.com/waistu/halo-theme-Wing"
  issues: "https://github.com/waistu/halo-theme-Wing/issues"
  settingName: "theme-Wing-setting"
  configMapName: "theme-Wing-configMap"
  version: "0.9.5"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 友情链接页面模板
        description: 适配友情链接模板
        file: links.html
      - name: 关于页面模板
        description: 自定义关于博主页面
        file: about.html
