apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-wing
  annotations:
    theme-wing/link-group-style: "友链卡片样式: default=默认, recommend=推荐, lost=失联"
spec:
  displayName: Wing
  author:
    name: 二歪同学
    website: "https://waistu.com"
  description: 一款简洁流畅、数据驱动，响应式主题，移植自WordPress主题Wing
  logo: "/themes/theme-wing/assets/images/logo.png"
  homepage: "https://github.com/waistu/halo-theme-Wing#readme"
  repo: "https://github.com/waistu/halo-theme-Wing"
  issues: "https://github.com/waistu/halo-theme-Wing/issues"
  settingName: "theme-wing-setting"
  configMapName: "theme-wing-configMap"
  version: "1.0.0"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 朋友圈页面模板
        description: 适配 Halo 朋友圈插件
        file: friends.html
      - name: 友链页面模板
        description: 适配 Halo 链接管理插件
        file: links.html
      - name: 关于页面模板
        description: 自定义关于博主页面
        file: about.html
